### ISSUE TITLE
Compatibility with phpbb 3.3.11

### ISSUE THREAD

**Issue by spanevin** [DavidIQ/ReIMG#24]
I just upgraded my 3.0.14 board to the latest 3.3.11. It was really painful because of lots of modifications were lost, and I'm trying to restore the most important ones.

I found that here is ReIMG Image Resizer extension port compatible with 3.3, so I tried to install it.

I can see admin settings (unfortunately, my language is not supported by this port, but it is not a big problem), but I don't see any changes in images in posts. Should it be working with 3.3.11 at all? Maybe there is some global on/off switch which I could miss?

**Comment by DavidIQ** [comment]
Hi there. It seems to work fine on 3.3.11 here: https://www.davidiq.com/support/viewtopic.php?t=353

Note that if you have thumbnails enabled it might not apply to images with thumbnails unless you enable the "Apply ReIMG zoom method to all posted images:" option.
